### ISSUE TITLE
mkdir with permissions 0555 fails

### ISSUE THREAD

**Issue by xqms** [containers/fuse-overlayfs#414]
This came up in https://github.com/apptainer/apptainer/issues/2033, where I'm trying to debug a problem with `nvidia-container-cli`.

`nvidia-container-cli` tries to create a directory with mode 0555 (`/etc/nvidia/nvidia-application-profiles-rc.d`), which fails with "Permission denied" in `fuse-overlayfs`.

Here is a minimal example showing the problem:
```sh
#!/bin/bash
mkdir lower upper work final
fuse-overlayfs -o "lowerdir=$(pwd)/lower,upperdir=$(pwd)/upper,workdir=$(pwd)/work" final
mkdir -m 0555 final/test || echo "mkdir failed!"
fusermount -u final
```

In contrast, the kernel overlay filesystem can handle this situation (replace fuse-overlayfs with `sudo mount -t overlay -o lowerdir=$(pwd)/lower,upperdir=$(pwd)/upper,workdir=$(pwd)/work none final` above).

I traced this problem to [here](https://github.com/containers/fuse-overlayfs/blob/c2dd76c6d7553971b7d2934c3bb4fa0b846e46b9/main.c#L2891), where a backing file with the specified mode is created. Later on the code tries to set extended attributes on this file [here](https://github.com/containers/fuse-overlayfs/blob/c2dd76c6d7553971b7d2934c3bb4fa0b846e46b9/main.c#L698), which fails due to the non-writable permissions.

Is this expected behavior? If not, is it possible to fix this in `fuse-overlayfs` by creating the backing file first with writable permissions and then later chmod()ing it to the final permissions?

**Comment by flouthoc** [comment]
I don't know why backing file needs to be equal to the `mode` since when directory is made `opaque`  while creating, `st_out` is always set which reverts back to the correct mode so I think we can always give `7xx` to the backing file.

@xqms I think following diff should fix this but I'll create a PR only once we can get ack from @giuseppe , patch works for me.
```diff
diff --git a/main.c b/main.c
index 3a49a1b..a3f82a4 100644
--- a/main.c
+++ b/main.c
@@ -2865,6 +2865,11 @@ create_directory (struct ovl_data *lo, int dirfd, const char *name, const struct
   char wd_tmp_file_name[32];
   bool need_rename;
   mode_t backing_file_mode = mode | (lo->xattr_permissions ? 0755 : 0);
+  if (set_opaque && st_out &&
+      (!(backing_file_mode & S_IWUSR) || !((backing_file_mode & S_IRUSR)) ||
+       !(backing_file_mode & S_IXUSR))) {
+    backing_file_mode = backing_file_mode | S_IWUSR | S_IRUSR | S_IXUSR;
+  }
 
   need_rename = set_opaque || times || xattr_sfd >= 0 || uid != lo->uid || gid != lo->gid || get_upper_layer (lo)->stat_override_mode != STAT_OVERRIDE_NONE;
   if (! need_rename)
```

**Comment by giuseppe** [comment]
fuse-overlayfs is usually used inside a user namespace where it runs with CAP_DAC_OVERRIDE.  Are you trying to use it directly on the host without any capability?

This use case is not well supported, because there are assumptions everywhere about the process being able to modify file permissions/ownership as it would be running with capabilities, even if restricted by a user namespace

**Comment by xqms** [comment]
Hmm, good point! As far as I know it runs in a user namespace created by apptainer, but maybe not with CAP_DAC_OVERRIDE... @DrDaveD might know more. I'll try to find out as well.

**Comment by xqms** [comment]
Yep, adding CAP_DAC_OVERRIDE (https://github.com/apptainer/apptainer/pull/2036) makes everything work. I guess this means that this can be fixed on the apptainer side and no changes to fuse-overlayfs are required, but I'll wait for @DrDaveD to confirm.

**Comment by DrDaveD** [comment]
That's exactly right.  Thanks for the pointer, Giuseppe.

**Comment by xqms** [comment]
Now fixed in apptainer, thanks for helping!
